"""D0-F exact-rational *calculation* records, not proof-carrying JSON.

Canonical records can be regenerated byte-for-byte from explicit finite inputs.
A self-declared digest detects inconsistent records, not adversarial replacement;
input identity requires a separately trusted expected problem digest.
"""
from __future__ import annotations

from fractions import Fraction
import hashlib
import json
import math
import re

from d0_finite_solver import RationalBitBudgetExceeded, solve_frozen_menu

SCHEMA = "permannsson.d0.finite-menu.v1"
SCOPE = "EXACT_FINITE_MENU_CALCULATION"
FAMILY = "CONSTRUCTED_UNIT_FIN_RESEARCH"
MAX_BYTES = 2_000_000
MAX_STATES = 12
MAX_CANDIDATES = 32
MAX_HORIZON = 128
MAX_INPUT_BITS = 256
MAX_VALUE_BITS = 8192
MAX_TRANSITIONS = 200_000
LABEL = re.compile(r"[A-Za-z][A-Za-z0-9_-]{0,63}\Z")


class CertificateError(ValueError):
    """Malformed, unsupported, or noncanonical finite problem/report."""


class CertificateResourceLimit(CertificateError):
    """Bounded verifier refuses costly input; this is not an invalid proof."""


def _integer(x, name, low=0, high=None):
    if type(x) is not int or x < low or (high is not None and x > high):
        raise CertificateError("invalid " + name)
    return x


def _fraction(x):
    if type(x) not in (int, Fraction):
        raise CertificateError("matrix entries must be int or Fraction")
    q = Fraction(x)
    if q.numerator.bit_length() > MAX_INPUT_BITS or q.denominator.bit_length() > MAX_INPUT_BITS:
        raise CertificateResourceLimit("matrix rational bit limit")
    return q


def fraction_pair(q):
    """Canonical exact fraction as [numerator, positive denominator]."""
    if type(q) not in (int, Fraction):
        raise CertificateError("not an exact rational")
    q = Fraction(q)
    if max(abs(q.numerator).bit_length(), q.denominator.bit_length()) > MAX_VALUE_BITS:
        raise CertificateResourceLimit("rational result bit limit")
    return [q.numerator, q.denominator]


def read_pair(value, *, input_entry=False):
    if type(value) is not list or len(value) != 2:
        raise CertificateError("fraction must be a [numerator,denominator] array")
    num = _integer_signed(value[0], "numerator")
    den = _integer(value[1], "denominator", low=1)
    if den <= 0 or math.gcd(num, den) != 1:
        raise CertificateError("noncanonical rational")
    maximum = MAX_INPUT_BITS if input_entry else MAX_VALUE_BITS
    if max(abs(num).bit_length(), den.bit_length()) > maximum:
        raise CertificateResourceLimit("rational bit limit")
    return Fraction(num, den)


def _integer_signed(value, name):
    if type(value) is not int:
        raise CertificateError("invalid " + name)
    return value


def _dimension(n):
    _integer(n, "dimension", low=1)
    if n > MAX_STATES:
        raise CertificateResourceLimit("state dimension limit")
    return n


def normalize_matrix(rows, n=None):
    if type(rows) not in (list, tuple):
        raise CertificateError("matrix must be a sequence")
    size = _dimension(len(rows))
    if n is not None and n != size:
        raise CertificateError("candidate matrices must share the state space")
    out = []
    for row in rows:
        if type(row) not in (list, tuple) or len(row) != size:
            raise CertificateError("matrix row not square")
        qs = tuple(_fraction(v) for v in row)
        if any(v < 0 for v in qs) or sum(qs, Fraction(0)) != 1:
            raise CertificateError("invalid stochastic row")
        out.append(qs)
    return tuple(out)


def _encode_matrix(matrix):
    return [[fraction_pair(q) for q in row] for row in matrix]


def _normalize_states(states, n, label):
    try:
        xs = tuple(states)
    except TypeError as exc:
        raise CertificateError("invalid " + label) from exc
    for x in xs:
        _integer(x, label + " index", low=0, high=n-1)
    return sorted(set(xs))


def _check_budget(n, horizon, candidates):
    _integer(horizon, "horizon", low=0)
    _integer(candidates, "candidate count", low=1)
    if horizon > MAX_HORIZON or candidates > MAX_CANDIDATES:
        raise CertificateResourceLimit("finite menu/horizon limit")
    if n * n * max(horizon, 1) * candidates > MAX_TRANSITIONS:
        raise CertificateResourceLimit("finite transition work limit")


def normalize_problem(menu, baseline, initial, goal, forbidden, horizon):
    # Materialize the menu once: callers may pass generators.
    try:
        members = tuple(menu)
    except TypeError as exc:
        raise CertificateError("invalid menu") from exc
    _check_budget(_dimension(len(baseline)), horizon, len(members))
    bmatrix = normalize_matrix(baseline)
    n = len(bmatrix)
    _integer(initial, "initial", low=0, high=n-1)
    g = _normalize_states(goal, n, "goal")
    d = _normalize_states(forbidden, n, "forbidden")
    if set(g).intersection(d):
        raise CertificateError("goal/forbidden overlap")
    output = []
    seen = set()
    for item in members:
        if type(item) not in (list, tuple) or len(item) != 2:
            raise CertificateError("menu entries must be (label,matrix)")
        name, rows = item
        if type(name) is not str or not LABEL.fullmatch(name) or name in seen:
            raise CertificateError("invalid or duplicate candidate label")
        seen.add(name)
        output.append({"label": name, "rows": _encode_matrix(normalize_matrix(rows, n))})
    return {
        "family": FAMILY,
        "dimension": n,
        "baseline_rows": _encode_matrix(bmatrix),
        "menu": output,
        "initial": initial,
        "goal": g,
        "forbidden": d,
        "horizon": horizon,
    }


def canonical_bytes(record):
    try:
        raw = (json.dumps(record, ensure_ascii=True, allow_nan=False,
            sort_keys=True, separators=(",", ":")) + "\n").encode("ascii")
    except (ValueError, TypeError, UnicodeError) as exc:
        raise CertificateError("nonserializable certificate") from exc
    if len(raw) > MAX_BYTES:
        raise CertificateResourceLimit("certificate byte limit")
    return raw


def problem_digest(problem):
    return hashlib.sha256(canonical_bytes(problem)).hexdigest()


def _decode_problem_for_solver(problem):
    return [
        (entry["label"], tuple(tuple(read_pair(p, input_entry=True)
                         for p in row) for row in entry["rows"]))
        for entry in problem["menu"]
    ]


def make_certificate(menu, baseline, initial, goal, forbidden, horizon):
    """Produce canonical bytes using D0's existing exact BACKWARD recursion."""
    problem = normalize_problem(menu, baseline, initial, goal, forbidden, horizon)
    normalized = _decode_problem_for_solver(problem)
    try:
        result = solve_frozen_menu(normalized, initial, problem["goal"],
                                   problem["forbidden"], horizon,
                                   max_rational_bits=MAX_VALUE_BITS)
    except RationalBitBudgetExceeded as exc:
        raise CertificateResourceLimit(str(exc)) from exc
    record = {
        "schema": SCHEMA,
        "scope": SCOPE,
        "problem": problem,
        "problem_sha256": problem_digest(problem),
        "calculation": {
            "values": [{"label": name, "value": fraction_pair(value)}
                       for name, value in result.values],
            "selected": result.selected,
            "value": fraction_pair(result.value),
        },
    }
    return canonical_bytes(record)


def parse_json_strict(raw):
    if type(raw) is not bytes or len(raw) > MAX_BYTES:
        raise CertificateResourceLimit("certificate byte limit or nonbytes input")
    def object_pairs(pairs):
        d = {}
        for k, v in pairs:
            if k in d:
                raise CertificateError("duplicate JSON key")
            d[k] = v
        return d
    def bad_constant(value):
        raise CertificateError("nonfinite JSON number: " + value)
    def bad_float(value):
        raise CertificateError("floating point JSON numbers forbidden")
    try:
        obj = json.loads(raw.decode("utf-8"), object_pairs_hook=object_pairs,
                         parse_float=bad_float, parse_constant=bad_constant)
    except (UnicodeDecodeError, json.JSONDecodeError, RecursionError) as exc:
        raise CertificateError("invalid JSON encoding") from exc
    if type(obj) is not dict or raw != canonical_bytes(obj):
        raise CertificateError("noncanonical JSON bytes")
    return obj
