import PermanssonResearch.GrammarRobust.BooleanOccupation
import PermanssonResearch.GrammarRobust.AtomicSelection
import PermanssonResearch.Compatibility
import PermanssonResearch.ConstitutiveQuasi.Definition
import PermanssonResearch.ConstitutiveQuasi.TrajectoryHelpers
import PermanssonResearch.ConstitutiveQuasi.PathOutput
import PermanssonResearch.ConstitutiveQuasi.BoundedTV
import PermanssonResearch.ConstitutiveQuasi.Counterexamples
import PermanssonResearch.ConstitutiveQuasi.InterventionPair
import PermanssonResearch.ConstitutiveQuasi.SurvivalRobustness
import PermanssonResearch.ConstitutiveQuasi.Certificate
import PermanssonResearch.ConstitutiveQuasi.PropertyErrors
import PermanssonResearch.ConstitutiveQuasi.Robustness
import PermanssonResearch.ConstitutiveQuasi.CertificateExamples
import PermanssonResearch.ConstitutiveQuasi.ComparisonTransport
import PermanssonResearch.ConstitutiveQuasi.PersistencePromotion
import PermanssonResearch.ConstitutiveQuasi.CertificateTransport
import PermanssonResearch.ConstitutiveQuasi.AdversarialExamples
import PermanssonResearch.ConstitutiveQuasi.NonzeroErrorExample
import PermanssonResearch.ReverseSolver.Target
import PermanssonResearch.ReverseSolver.FrozenMenu
import PermanssonResearch.ReverseSolver.MenuExamples
import PermanssonResearch.ReverseSolver.RationalKernel
import PermanssonResearch.ReverseSolver.CertifiedSelection
import PermanssonResearch.ReverseSolver.ValueCorrespondence
import PermanssonResearch.ReverseSolver.FiniteEvaluation
import PermanssonResearch.ReverseSolver.CertificationExamples
import PermanssonResearch.ReverseSolver.CanonicalFiniteKernel
import PermanssonResearch.ReverseSolver.FinitePrefixBridge
import PermanssonResearch.ReverseSolver.CanonicalProjectivity
import PermanssonResearch.ReverseSolver.CanonicalTransitionPair
import PermanssonResearch.ReverseSolver.CanonicalAtomMass
import PermanssonResearch.ReverseSolver.CanonicalEventSum
import PermanssonResearch.ReverseSolver.CanonicalHistoryWeight
import PermanssonResearch.ReverseSolver.CanonicalHistoryAtoms
import PermanssonResearch.ReverseSolver.CanonicalWordEncoding
import PermanssonResearch.ReverseSolver.AnchoredHistoryEquiv
import PermanssonResearch.ReverseSolver.RationalHistoryProduct
import PermanssonResearch.ReverseSolver.WordEnumerationBridge
import PermanssonResearch.ReverseSolver.CanonicalVectorSuccess
import PermanssonResearch.ReverseSolver.CanonicalEventVectorEquiv
import PermanssonResearch.ReverseSolver.CanonicalWordEvent
import PermanssonResearch.ReverseSolver.CanonicalWordMass
import PermanssonResearch.ReverseSolver.CanonicalFiniteEventSum
import PermanssonResearch.ReverseSolver.CanonicalAllHorizonCorrespondence
import PermanssonResearch.ReverseSolver.CanonicalCertificationExamples
import PermanssonResearch.ReverseSolver.FiniteStrategicRealization
import PermanssonResearch.ReverseSolver.FiniteStrategicRealizationExamples
import PermanssonResearch.ReverseSolver.GenericFinitePrefixAtoms
import PermanssonResearch.ReverseSolver.FiniteStrategicPathBridge
import PermanssonResearch.ReverseSolver.TypedMenuCertification
import PermanssonResearch.ReverseSolver.TypedMenuCertificationExamples
import PermanssonResearch.ReverseSolver.EndToEndCertificate
import PermanssonResearch.ReverseSolver.ControlledKernel
import PermanssonResearch.ReverseSolver.ControlledKernelCorrespondence
import PermanssonResearch.ReverseSolver.ControlledKernelExamples
import PermanssonResearch.ReverseSolver.Bellman
import PermanssonResearch.ReverseSolver.BellmanPolicyValue
import PermanssonResearch.ReverseSolver.BellmanOptimality
import PermanssonResearch.ReverseSolver.BellmanExamples
import PermanssonResearch.ReverseSolver.NonstationaryPrefixKernel
import PermanssonResearch.ReverseSolver.NonstationaryPathAtoms
import PermanssonResearch.ReverseSolver.NonstationaryHitting
import PermanssonResearch.ReverseSolver.NonstationaryForward
import PermanssonResearch.ReverseSolver.NonstationaryOptimality
import PermanssonResearch.ReverseSolver.NonstationaryExamples
import PermanssonResearch.ReverseSolver.NonstationaryTypedKernel
import PermanssonResearch.ReverseSolver.NonstationaryTypedPrefix
import PermanssonResearch.ReverseSolver.NonstationaryTypedAtoms
import PermanssonResearch.ReverseSolver.NonstationaryTypedTransport
import PermanssonResearch.ReverseSolver.NonstationaryTypedHitting
import PermanssonResearch.ReverseSolver.NonstationaryTypedExamples
import PermanssonResearch.ReverseSolver.HistoryPolicy
import PermanssonResearch.ReverseSolver.HistoryPrefixKernel
import PermanssonResearch.ReverseSolver.HistoryPathAtoms
import PermanssonResearch.ReverseSolver.HistoryEventValue
import PermanssonResearch.ReverseSolver.HistoryContinuation
import PermanssonResearch.ReverseSolver.HistoryStatusBridge
import PermanssonResearch.ReverseSolver.HistoryForwardBridge
import PermanssonResearch.ReverseSolver.HistoryForwardMeasure
import PermanssonResearch.ReverseSolver.HistoryBellmanDominance
import PermanssonResearch.ReverseSolver.HistoryPolicyExamples
import PermanssonResearch.ReverseSolver.HistoryTypedFeedback
import PermanssonResearch.ReverseSolver.HistoryTypedKernel
import PermanssonResearch.ReverseSolver.HistoryTypedPrefix
import PermanssonResearch.ReverseSolver.HistoryTypedAtoms
import PermanssonResearch.ReverseSolver.HistoryTypedTransport
import PermanssonResearch.ReverseSolver.HistoryTypedHitting
import PermanssonResearch.ReverseSolver.HistoryTypedExamples

import PermanssonResearch.GrammarRobust.AtomicBank
import PermanssonResearch.GrammarRobust.AtomicApply
import PermanssonResearch.GrammarRobust.PartitionGrammar
import PermanssonResearch.GrammarRobust.BlockModels

import PermanssonResearch.GrammarRobust.OriginalInterventionBridge
import PermanssonResearch.GrammarRobust.Refinement

import PermanssonResearch.GrammarRobust.BlockConstitution
import PermanssonResearch.GrammarRobust.RefinementTransport

import PermanssonResearch.GrammarRobust.BooleanModel

import PermanssonResearch.GrammarRobust.Minimality

import PermanssonResearch.GrammarRobust.AtomicLocality

import PermanssonResearch.GrammarRobust.IsomorphicTransport

import PermanssonResearch.GrammarRobust.EffectTransport

import PermanssonResearch.GrammarRobust.BooleanBaseline

/-!
# PermanssonResearch

Research-only library root. New mathematical extensions belong in this separate
import tree and require independently reviewed theorem and counterexample gates.
Importing this library does not strengthen the frozen v0.1.8 core.
-/
