import PermanssonLean.StrategicWorld.InducedKernel
import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.Process.FiniteDimensionalLaws

/-!
# Canonical path law for a strategic-world model

This module lifts the proved one-step kernel `StrategicWorldModel.inducedKernel`
to the canonical infinite trajectory law by Ionescu--Tulcea.  It also records the
finite-history transition identity and, under standard-Borel hypotheses, the regular
conditional transition statement.
-/

open Finset MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

namespace PermanssonLean

universe uS uX uA

variable {S : Type uS} {X : Type uX} {A : Type uA}
variable [MeasurableSpace S] [MeasurableSpace X] [MeasurableSpace A]

namespace StrategicWorldModel

/-- Lift a stationary one-step kernel to finite histories by reading only the most
recent coordinate. -/
noncomputable def stationaryHistoryKernel
    (K : Kernel (JointState S X) (JointState S X)) (n : ℕ) :
    Kernel ((i : Iic n) → JointState S X) (JointState S X) :=
  K.comap (fun h => h ⟨n, mem_Iic.mpr le_rfl⟩) (by fun_prop)

instance stationaryHistoryKernel_isMarkov
    (K : Kernel (JointState S X) (JointState S X)) [IsMarkovKernel K] (n : ℕ) :
    IsMarkovKernel (stationaryHistoryKernel K n) := by
  unfold stationaryHistoryKernel
  infer_instance

/-- Canonical trajectory law generated by a strategic-world model and initial law. -/
noncomputable def pathLaw
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    Measure (ℕ → JointState S X) := by
  letI : IsMarkovKernel M.inducedKernel := inducedKernel_isMarkov M
  exact Kernel.trajMeasure mu0 (fun n => stationaryHistoryKernel M.inducedKernel n)

instance pathLaw_isProbability
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    IsProbabilityMeasure (M.pathLaw mu0) := by
  letI : IsMarkovKernel M.inducedKernel := inducedKernel_isMarkov M
  unfold pathLaw
  infer_instance

/-- Finite-history transition identity for a stationary kernel. -/
def HasTransitionPair
    (mu : Measure (ℕ → JointState S X))
    (K : Kernel (JointState S X) (JointState S X)) : Prop :=
  ∀ n : ℕ,
    (mu.map (Preorder.frestrictLe n)) ⊗ₘ stationaryHistoryKernel K n =
      mu.map (fun w : ℕ → JointState S X => (Preorder.frestrictLe n w, w (n + 1)))

/-- The canonical path law satisfies the finite-history transition identity for the
model's induced kernel. -/
theorem pathLaw_has_transition_pair
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    HasTransitionPair (M.pathLaw mu0) M.inducedKernel := by
  letI : IsMarkovKernel M.inducedKernel := inducedKernel_isMarkov M
  intro n
  simpa [pathLaw] using
    (Kernel.map_frestrictLe_trajMeasure_compProd_eq_map_trajMeasure
      (X := fun _ : ℕ => JointState S X)
      (κ := fun k => stationaryHistoryKernel M.inducedKernel k) (μ₀ := mu0) (a := n))

/-- The zeroth finite-history marginal of the canonical path law is exactly the
initial law, written in the singleton-product representation used by
Ionescu--Tulcea. -/
theorem pathLaw_prefix_zero
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    (M.pathLaw mu0).map (Preorder.frestrictLe 0) =
      mu0.map (MeasurableEquiv.piUnique (fun _ : Iic 0 => JointState S X)).symm := by
  letI : IsMarkovKernel M.inducedKernel := inducedKernel_isMarkov M
  unfold pathLaw Kernel.trajMeasure
  rw [Measure.map_comp _ _ (by fun_prop)]
  rw [Kernel.traj_map_frestrictLe]
  simp

/-- Under the canonical path law, the regular conditional distribution of the next
joint state given the finite history is the stationary induced kernel evaluated at
the most recent state. Standard-Borel assumptions are explicit because this is an
RCD statement, not merely a finite-dimensional identity. -/
theorem pathLaw_has_transition
    [StandardBorelSpace S] [StandardBorelSpace X] [Nonempty S] [Nonempty X]
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] (n : ℕ) :
    condDistrib
        (fun w : ℕ → JointState S X => w (n + 1))
        (Preorder.frestrictLe n)
        (M.pathLaw mu0)
      =ᵐ[(M.pathLaw mu0).map (Preorder.frestrictLe n)]
        stationaryHistoryKernel M.inducedKernel n := by
  letI : IsMarkovKernel M.inducedKernel := inducedKernel_isMarkov M
  simpa [pathLaw] using
    (Kernel.condDistrib_trajMeasure
      (X := fun _ : ℕ => JointState S X)
      (κ := fun k => stationaryHistoryKernel M.inducedKernel k) (μ₀ := mu0) (a := n))

end StrategicWorldModel

end PermanssonLean
