import PermanssonLean.StrategicWorld.PathLaw

/-!
# Joint-process well-posedness

Existence and uniqueness of the infinite strategic-world trajectory law generated by
`StrategicWorldModel.inducedKernel`.  The uniqueness proof first identifies every
finite prefix law and then upgrades those equalities to equality of the full
trajectory measures by projective-limit uniqueness.
-/

open Finset MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

namespace PermanssonLean

universe uS uX uA

variable {S : Type uS} {X : Type uX} {A : Type uA}
variable [MeasurableSpace S] [MeasurableSpace X] [MeasurableSpace A]

namespace StrategicWorldModel

/-- Append one new joint state to a finite path prefix. -/
def appendPrefix (n : ℕ)
    (z : ((i : Iic n) → JointState S X) × JointState S X) :
    (i : Iic (n + 1)) → JointState S X :=
  fun i => if h : i.1 ≤ n then z.1 ⟨i.1, mem_Iic.mpr h⟩ else z.2

theorem measurable_appendPrefix (n : ℕ) :
    Measurable (appendPrefix (S := S) (X := X) n) := by
  refine Measurable.of_eval fun i => ?_
  by_cases h : i.1 ≤ n
  · simp only [appendPrefix, dif_pos h]
    exact (measurable_pi_apply (⟨i.1, mem_Iic.mpr h⟩ : Iic n)).comp measurable_fst
  · simp only [appendPrefix, dif_neg h]
    exact measurable_snd

/-- Appending coordinate `n+1` to the prefix through `n` recovers the prefix
through `n+1`. -/
theorem appendPrefix_pair (n : ℕ) (w : ℕ → JointState S X) :
    appendPrefix (S := S) (X := X) n
        (Preorder.frestrictLe n w, w (n + 1)) =
      Preorder.frestrictLe (n + 1) w := by
  funext i
  by_cases h : i.1 ≤ n
  · simp [appendPrefix, h]
  · have hi : i.1 = n + 1 := by
      have hle : i.1 ≤ n + 1 := mem_Iic.mp i.2
      omega
    simp [appendPrefix, hi]

/-- Two laws with the same zeroth prefix and the same transition-pair identities
have the same finite-prefix law at every time. -/
theorem prefix_maps_eq_of_initial_and_transition
    {mu nu : Measure (ℕ → JointState S X)}
    (K : Kernel (JointState S X) (JointState S X))
    (h0 : mu.map (Preorder.frestrictLe 0) = nu.map (Preorder.frestrictLe 0))
    (hmu : HasTransitionPair mu K)
    (hnu : HasTransitionPair nu K) :
    ∀ n : ℕ, mu.map (Preorder.frestrictLe n) = nu.map (Preorder.frestrictLe n) := by
  intro n
  induction n with
  | zero => exact h0
  | succ n ih =>
      have hpair :
          mu.map (fun w : ℕ → JointState S X =>
              (Preorder.frestrictLe n w, w (n + 1))) =
            nu.map (fun w : ℕ → JointState S X =>
              (Preorder.frestrictLe n w, w (n + 1))) := by
        rw [← hmu n, ← hnu n, ih]
      calc
        mu.map (Preorder.frestrictLe (n + 1)) =
            (mu.map (fun w : ℕ → JointState S X =>
              (Preorder.frestrictLe n w, w (n + 1)))).map
                (appendPrefix (S := S) (X := X) n) := by
          rw [Measure.map_map (measurable_appendPrefix (S := S) (X := X) n) (by fun_prop)]
          apply Measure.map_congr
          filter_upwards [] with w
          exact (appendPrefix_pair (S := S) (X := X) n w).symm
        _ = (nu.map (fun w : ℕ → JointState S X =>
              (Preorder.frestrictLe n w, w (n + 1)))).map
                (appendPrefix (S := S) (X := X) n) := by
          rw [hpair]
        _ = nu.map (Preorder.frestrictLe (n + 1)) := by
          rw [Measure.map_map (measurable_appendPrefix (S := S) (X := X) n) (by fun_prop)]
          apply Measure.map_congr
          filter_upwards [] with w
          exact appendPrefix_pair (S := S) (X := X) n w

/-- Equality of all initial-segment laws determines a probability law on the
countable trajectory space. -/
theorem measure_eq_of_prefix_maps_eq
    (mu nu : Measure (ℕ → JointState S X))
    [IsProbabilityMeasure mu] [IsProbabilityMeasure nu]
    (h : ∀ n : ℕ,
      mu.map (Preorder.frestrictLe n) = nu.map (Preorder.frestrictLe n)) :
    mu = nu := by
  let fam : (I : Finset ℕ) →
      Measure ((i : I) → (fun _ : ℕ => JointState S X) i) :=
    fun I => mu.map (fun w : ℕ → JointState S X => I.restrict w)
  have hfam : IsProjectiveMeasureFamily
      (α := fun _ : ℕ => JointState S X) fam := by
    dsimp [fam]
    apply ProbabilityTheory.isProjectiveMeasureFamily_map_restrict
    intro t
    exact (measurable_pi_apply t).aemeasurable
  have hmu : IsProjectiveLimit
      (α := fun _ : ℕ => JointState S X) mu fam := by
    intro I
    rfl
  have hnu : IsProjectiveLimit
      (α := fun _ : ℕ => JointState S X) nu fam := by
    rw [MeasureTheory.isProjectiveLimit_nat_iff hfam]
    intro n
    change nu.map (Preorder.frestrictLe n) =
      mu.map (Preorder.frestrictLe n)
    exact (h n).symm
  haveI (I : Finset ℕ) : IsFiniteMeasure (fam I) := by
    dsimp [fam]
    infer_instance
  exact hmu.unique hnu

/-- Machine-level specification of the strategic-world trajectory law.

It requires:
1. a probability law on infinite trajectories;
2. the declared initial law;
3. the stationary transition-pair identity for the model's exact induced kernel.
-/
def MarkovPathLawSpec
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    (mu : Measure (ℕ → JointState S X)) : Prop :=
  IsProbabilityMeasure mu ∧
    mu.map (Preorder.frestrictLe 0) =
      mu0.map (MeasurableEquiv.piUnique
        (fun _ : Iic 0 => JointState S X)).symm ∧
    HasTransitionPair mu M.inducedKernel

/-- The Ionescu--Tulcea path law satisfies the exact model-level path-law spec. -/
theorem pathLaw_spec
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    MarkovPathLawSpec M mu0 (M.pathLaw mu0) := by
  exact ⟨inferInstance, pathLaw_prefix_zero M mu0,
    pathLaw_has_transition_pair M mu0⟩

/-- For the model's exact induced Markov kernel and any initial probability law,
there is exactly one trajectory probability law satisfying the declared initial
and transition identities. -/
theorem pathLaw_existsUnique
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    ∃! mu : Measure (ℕ → JointState S X),
      MarkovPathLawSpec M mu0 mu := by
  refine ⟨M.pathLaw mu0, pathLaw_spec M mu0, ?_⟩
  intro nu hnu
  letI : IsProbabilityMeasure nu := hnu.1
  have hEq : M.pathLaw mu0 = nu := by
    apply measure_eq_of_prefix_maps_eq (M.pathLaw mu0) nu
    apply prefix_maps_eq_of_initial_and_transition M.inducedKernel
    · exact (pathLaw_prefix_zero M mu0).trans hnu.2.1.symm
    · exact pathLaw_has_transition_pair M mu0
    · exact hnu.2.2
  exact hEq.symm

/-- Joint-process well-posedness for the canonical v0.1.7 strategic-world model:
its typed components induce a Markov kernel, and every initial probability law
induces one and only one probability law on infinite joint-state trajectories. -/
theorem joint_process_well_posed
    (M : StrategicWorldModel S X A)
    (mu0 : Measure (JointState S X))
    [IsProbabilityMeasure mu0] :
    IsMarkovKernel M.inducedKernel ∧
      ∃! mu : Measure (ℕ → JointState S X),
        MarkovPathLawSpec M mu0 mu := by
  exact ⟨inducedKernel_isMarkov M, pathLaw_existsUnique M mu0⟩


/-- Proposition 3.2 (enlarged-state reduction): every canonical strategic-world
model induces an ordinary Markov process on the joint state space `S × X`. -/
theorem enlarged_state_reduction
    (M : StrategicWorldModel S X A) :
    IsMarkovKernel M.inducedKernel :=
  inducedKernel_isMarkov M

end StrategicWorldModel

end PermanssonLean
