import PermanssonLean.Regime.PolishDescriptor
import Mathlib.Probability.Kernel.Deterministic
import Mathlib.MeasureTheory.Measure.Count

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal ProbabilityTheory Topology

namespace PermanssonLean

open RegimeSpecification

/-!
# Proposition 8.1: periodic Exact Generated Regime

This module formalizes the literal two-state example from Section 8.1 of
Permansson v0.1.7.  We encode 0/1 by Bool false/true.
-/

namespace PeriodicExactGR

noncomputable section

abbrev Bit := Bool
abbrev Y := JointState Bit Bit

def p0 : Y := (false, false)
def p1 : Y := (true, true)

def flipBit (b : Bit) : Bit := !b

def step (y : Y) : Y := (flipBit y.1, flipBit y.1)

@[simp] theorem step_p0 : step p0 = p1 := by
  rfl

@[simp] theorem step_p1 : step p1 = p0 := by
  rfl

def actionKernel : Kernel Y Bit :=
  Kernel.deterministic (fun y => y.1) (by fun_prop)

def worldKernel : Kernel (WorldInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.2) (by fun_prop)

def updateKernel : Kernel (UpdateInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.1.1.1) (by fun_prop)

def generator : StrategicGenerator Bit Bit Bit where
  action := actionKernel
  update := updateKernel
  action_isMarkov := by
    unfold actionKernel
    infer_instance
  update_isMarkov := by
    unfold updateKernel
    infer_instance

def model : StrategicWorldModel Bit Bit Bit where
  generator := generator
  world := worldKernel
  world_isMarkov := by
    unfold worldKernel
    infer_instance

theorem inducedKernel_eq_dirac_step (y : Y) :
    model.inducedKernel y = Measure.dirac (step y) := by
  ext E hE
  rw [StrategicWorldModel.inducedKernel_apply model y hE]
  simp [model, generator, actionKernel, worldKernel, updateKernel, step,
    flipBit, Kernel.deterministic_apply]
  by_cases hmem : step y ∈ E <;> simp [hmem, step, flipBit]

def region : Set Y := {p0, p1}

def basin : Set Y := region

def phase : Fin 2 → Y
  | ⟨0, _⟩ => p0
  | ⟨1, _⟩ => p1

noncomputable def target : ProbabilityMeasure Y :=
  (RegimeSpecification.uniformFinProbability 2 (by norm_num)).map phase

noncomputable def spec : RegimeSpecification Y Y where
  region := region
  region_measurable := MeasurableSet.of_discrete
  basin := basin
  basin_measurable := MeasurableSet.of_discrete
  basin_subset_region := by
    intro y hy
    exact hy
  descriptor := id
  descriptor_measurable := measurable_id
  target := target
  convergenceMode := ConvergenceMode.almostSureWeak Y Y

noncomputable def referenceMeasure : Measure Y :=
  Measure.count

@[simp] theorem p0_mem_region : p0 ∈ region := by
  simp [region]

@[simp] theorem p1_mem_region : p1 ∈ region := by
  simp [region]

theorem region_cases {y : Y} (hy : y ∈ region) :
    y = p0 ∨ y = p1 := by
  simpa [region] using hy

theorem step_mem_region {y : Y} (hy : y ∈ region) :
    step y ∈ region := by
  rcases region_cases hy with rfl | rfl <;> simp

theorem exactlyInvariant :
    IsExactlyInvariant model spec := by
  intro y hy
  rw [inducedKernel_eq_dirac_step]
  rw [Measure.dirac_apply_of_mem]
  exact step_mem_region hy

theorem basinHasTwoStates :
    BasinHasTwoStates spec := by
  refine ⟨p0, ?_, p1, ?_, ?_⟩
  · simp [spec, basin, region]
  · simp [spec, basin, region]
  · decide

theorem assumption41 :
    Assumption41 model spec referenceMeasure := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact ⟨p0, by simp [spec, basin, region]⟩
  · left
    refine ⟨p0, ?_⟩
    simp [spec, region]
  · refine ⟨p0, by simp [spec, region], p1, by simp [spec, region], ?_⟩
    decide
  · exact two_states_implies_basinPathLawNontrivial model spec basinHasTwoStates

/-- Deterministic alternating orbit generated by the Section 8.1 transition. -/
def orbit (y : Y) : ℕ → Y
  | 0 => y
  | n + 1 => step (orbit y n)

@[simp] theorem orbit_zero (y : Y) : orbit y 0 = y := rfl

@[simp] theorem orbit_succ (y : Y) (n : ℕ) :
    orbit y (n + 1) = step (orbit y n) := rfl

@[simp] theorem orbit_p0_even (n : ℕ) :
    orbit p0 (2 * n) = p0 := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [Nat.mul_succ, Nat.mul_one, Nat.add_assoc]
      simp only [Nat.add_comm 2 (2 * n)]
      rw [show 2 * n + 2 = (2 * n + 1) + 1 by omega]
      simp [orbit_succ, ih]

end

end PeriodicExactGR

end PermanssonLean
