import PermanssonLean.Regime.PolishDescriptor
import Mathlib.Probability.Kernel.Deterministic
import Mathlib.MeasureTheory.Measure.Count
import Mathlib.MeasureTheory.Integral.Bochner.SumMeasure
import Mathlib.Analysis.SpecificLimits.Basic

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal ProbabilityTheory Topology

namespace PermanssonLean

open RegimeSpecification

/-!
# Proposition 8.1: periodic Exact Generated Regime

This module formalizes the literal two-state example from Section 8.1 of
Permansson v0.1.7.  We encode 0/1 by Bool false/true.
-/

namespace PeriodicExactGR

noncomputable section

abbrev Bit := Bool
abbrev Y := JointState Bit Bit

def p0 : Y := (false, false)
def p1 : Y := (true, true)

def flipBit (b : Bit) : Bit := !b

def step (y : Y) : Y := (flipBit y.1, flipBit y.1)

@[simp] theorem step_p0 : step p0 = p1 := by
  rfl

@[simp] theorem step_p1 : step p1 = p0 := by
  rfl

def actionKernel : Kernel Y Bit :=
  Kernel.deterministic (fun y => y.1) (by fun_prop)

def worldKernel : Kernel (WorldInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.2) (by fun_prop)

def updateKernel : Kernel (UpdateInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.1.1.1) (by fun_prop)

def generator : StrategicGenerator Bit Bit Bit where
  action := actionKernel
  update := updateKernel
  action_isMarkov := by
    unfold actionKernel
    infer_instance
  update_isMarkov := by
    unfold updateKernel
    infer_instance

def model : StrategicWorldModel Bit Bit Bit where
  generator := generator
  world := worldKernel
  world_isMarkov := by
    unfold worldKernel
    infer_instance

theorem inducedKernel_eq_dirac_step (y : Y) :
    model.inducedKernel y = Measure.dirac (step y) := by
  ext E hE
  rw [StrategicWorldModel.inducedKernel_apply model y hE]
  simp [model, generator, actionKernel, worldKernel, updateKernel, step,
    flipBit, Kernel.deterministic_apply]
  by_cases hmem : step y ∈ E <;> simp [hmem, step, flipBit]

def region : Set Y := {p0, p1}

def basin : Set Y := region

def phase : Fin 2 → Y
  | ⟨0, _⟩ => p0
  | ⟨1, _⟩ => p1

/-- Equation (20): the equally weighted occupation law on the two-cycle. -/
noncomputable def targetMeasure : Measure Y :=
  (1 / 2 : ℝ≥0∞) • Measure.dirac p0 +
    (1 / 2 : ℝ≥0∞) • Measure.dirac p1

instance targetMeasure_isProbability :
    IsProbabilityMeasure targetMeasure := by
  refine ⟨?_⟩
  simp [targetMeasure]
  norm_num

noncomputable def target : ProbabilityMeasure Y :=
  targetMeasure.toProbabilityMeasure

@[simp] theorem target_toMeasure :
    target.toMeasure = targetMeasure := by
  rfl

noncomputable def spec : RegimeSpecification Y Y where
  region := region
  region_measurable := MeasurableSet.of_discrete
  basin := basin
  basin_measurable := MeasurableSet.of_discrete
  basin_subset_region := by
    intro y hy
    exact hy
  descriptor := id
  descriptor_measurable := measurable_id
  target := target
  convergenceMode := ConvergenceMode.almostSureWeak Y Y

noncomputable def referenceMeasure : Measure Y :=
  Measure.count

@[simp] theorem p0_mem_region : p0 ∈ region := by
  simp [region]

@[simp] theorem p1_mem_region : p1 ∈ region := by
  simp [region]

theorem region_cases {y : Y} (hy : y ∈ region) :
    y = p0 ∨ y = p1 := by
  simpa [region] using hy

theorem step_mem_region {y : Y} (hy : y ∈ region) :
    step y ∈ region := by
  rcases region_cases hy with rfl | rfl <;> simp

theorem exactlyInvariant :
    IsExactlyInvariant model spec := by
  intro y hy
  rw [inducedKernel_eq_dirac_step]
  rw [Measure.dirac_apply_of_mem]
  exact step_mem_region hy

theorem basinHasTwoStates :
    BasinHasTwoStates spec := by
  refine ⟨p0, ?_, p1, ?_, ?_⟩
  · simp [spec, basin, region]
  · simp [spec, basin, region]
  · decide

theorem assumption41 :
    Assumption41 model spec referenceMeasure := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact ⟨p0, by simp [spec, basin, region]⟩
  · left
    refine ⟨p0, ?_⟩
    simp [spec, region]
  · refine ⟨p0, by simp [spec, region], p1, by simp [spec, region], ?_⟩
    decide
  · exact two_states_implies_basinPathLawNontrivial model spec basinHasTwoStates

/-- Deterministic alternating orbit generated by the Section 8.1 transition. -/
def orbit (y : Y) : ℕ → Y
  | 0 => y
  | n + 1 => step (orbit y n)

@[simp] theorem orbit_zero (y : Y) : orbit y 0 = y := rfl

@[simp] theorem orbit_succ (y : Y) (n : ℕ) :
    orbit y (n + 1) = step (orbit y n) := rfl

@[simp] theorem orbit_p0_even (n : ℕ) :
    orbit p0 (2 * n) = p0 := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [Nat.mul_succ, Nat.mul_one, Nat.add_assoc]
      simp only [Nat.add_comm 2 (2 * n)]
      rw [show 2 * n + 2 = (2 * n + 1) + 1 by omega]
      simp [orbit_succ, ih]


@[simp] theorem orbit_p0_odd (n : ℕ) :
    orbit p0 (2 * n + 1) = p1 := by
  rw [orbit_succ, orbit_p0_even]
  rfl

@[simp] theorem orbit_p1_even (n : ℕ) :
    orbit p1 (2 * n) = p1 := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [show 2 * (n + 1) = (2 * n + 1) + 1 by omega]
      rw [orbit_succ, orbit_succ, ih]
      rfl

@[simp] theorem orbit_p1_odd (n : ℕ) :
    orbit p1 (2 * n + 1) = p0 := by
  rw [orbit_succ, orbit_p1_even]
  rfl

theorem sum_orbit_p0_even (f : Y → ℝ) (n : ℕ) :
    ∑ i ∈ Finset.range (2 * n), f (orbit p0 i) =
      n * (f p0 + f p1) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [show 2 * (n + 1) = 2 * n + 2 by omega]
      rw [show 2 * n + 2 = (2 * n + 1) + 1 by omega]
      rw [Finset.sum_range_succ, Finset.sum_range_succ, ih]
      simp [orbit_p0_even, orbit_p0_odd]
      ring

theorem sum_orbit_p0_odd (f : Y → ℝ) (n : ℕ) :
    ∑ i ∈ Finset.range (2 * n + 1), f (orbit p0 i) =
      n * (f p0 + f p1) + f p0 := by
  rw [Finset.sum_range_succ, sum_orbit_p0_even]
  simp

theorem sum_orbit_p1_even (f : Y → ℝ) (n : ℕ) :
    ∑ i ∈ Finset.range (2 * n), f (orbit p1 i) =
      n * (f p0 + f p1) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [show 2 * (n + 1) = 2 * n + 2 by omega]
      rw [show 2 * n + 2 = (2 * n + 1) + 1 by omega]
      rw [Finset.sum_range_succ, Finset.sum_range_succ, ih]
      simp [orbit_p1_even, orbit_p1_odd]
      ring

theorem sum_orbit_p1_odd (f : Y → ℝ) (n : ℕ) :
    ∑ i ∈ Finset.range (2 * n + 1), f (orbit p1 i) =
      n * (f p0 + f p1) + f p1 := by
  rw [Finset.sum_range_succ, sum_orbit_p1_even]
  simp


theorem uniformFinProbability_toMeasure
    (T : ℕ) (hT : 0 < T) :
    (RegimeSpecification.uniformFinProbability T hT).toMeasure =
      ((T : ℝ≥0∞)⁻¹) • Measure.count := by
  ext E hE
  change ProbabilityTheory.uniformOn (Set.univ : Set (Fin T)) E =
    (((T : ℝ≥0∞)⁻¹) • Measure.count) E
  rw [ProbabilityTheory.uniformOn_univ, Measure.smul_apply]
  simp [ENNReal.div_eq_inv_mul, mul_comm]

/-- Empirical occupation integrals are ordinary finite arithmetic means. -/
theorem integral_empiricalOccupation_eq_average
    (w : ℕ → Y) (T : ℕ) (hT : 0 < T) (f : Y → ℝ) :
    ∫ y, f y ∂(RegimeSpecification.empiricalOccupation spec w T hT) =
      ((T : ℝ)⁻¹) * ∑ i : Fin T, f (w i) := by
  change
    ∫ y, f y ∂
      ((RegimeSpecification.uniformFinProbability T hT).map
        (fun i : Fin T => spec.descriptor (w (i : ℕ)))) =
      ((T : ℝ)⁻¹) * ∑ i : Fin T, f (w i)
  rw [integral_map (by fun_prop) (by fun_prop)]
  rw [uniformFinProbability_toMeasure T hT]
  rw [integral_smul_measure, integral_count]
  simp [spec, ENNReal.toReal_inv, smul_eq_mul]

theorem integral_target_eq_half_sum (f : Y → ℝ) :
    ∫ y, f y ∂target = (f p0 + f p1) / 2 := by
  change ∫ y, f y ∂targetMeasure = _
  simp [targetMeasure, div_eq_mul_inv]
  ring


/-- A sequence converges if its even and odd subsequences have the same limit. -/
theorem tendsto_of_even_odd
    {Z : Type*} [TopologicalSpace Z] {u : ℕ → Z} {z : Z}
    (he : Tendsto (fun n => u (2 * n)) atTop (𝓝 z))
    (ho : Tendsto (fun n => u (2 * n + 1)) atTop (𝓝 z)) :
    Tendsto u atTop (𝓝 z) := by
  rw [tendsto_def] at he ho ⊢
  intro s hs
  have hes := he s hs
  have hos := ho s hs
  rw [eventually_atTop] at hes hos ⊢
  obtain ⟨Ne, hNe⟩ := hes
  obtain ⟨No, hNo⟩ := hos
  refine ⟨2 * max Ne No + 1, ?_⟩
  intro n hn
  rcases Nat.even_or_odd n with hEven | hOdd
  · rcases hEven with ⟨k, hk⟩
    have hkN : Ne ≤ k := by omega
    simpa [hk, two_mul] using hNe k hkN
  · rcases hOdd with ⟨k, hk⟩
    have hkN : No ≤ k := by omega
    simpa [hk] using hNo k hkN

theorem tendsto_inv_odd_nat :
    Tendsto
      (fun n : ℕ => (1 : ℝ) / ((2 * n + 1 : ℕ) : ℝ))
      atTop (𝓝 0) := by
  have hidx : Tendsto (fun n : ℕ => 2 * n + 1) atTop atTop := by
    apply tendsto_atTop.2
    intro N
    filter_upwards [eventually_ge_atTop N] with n hn
    omega
  exact tendsto_one_div_atTop_nhds_zero_nat.comp hidx

theorem odd_average_p0_identity (a b : ℝ) (n : ℕ) :
    (((2 * n + 1 : ℕ) : ℝ)⁻¹) *
        ((n : ℝ) * (a + b) + a) =
      (a + b) / 2 +
        ((a - b) / 2) * (1 / ((2 * n + 1 : ℕ) : ℝ)) := by
  have hden : (((2 * n + 1 : ℕ) : ℝ)) ≠ 0 := by positivity
  field_simp [hden]
  ring

theorem odd_average_p1_identity (a b : ℝ) (n : ℕ) :
    (((2 * n + 1 : ℕ) : ℝ)⁻¹) *
        ((n : ℝ) * (a + b) + b) =
      (a + b) / 2 +
        ((b - a) / 2) * (1 / ((2 * n + 1 : ℕ) : ℝ)) := by
  have hden : (((2 * n + 1 : ℕ) : ℝ)) ≠ 0 := by positivity
  field_simp [hden]
  ring

theorem tendsto_odd_average_p0 (a b : ℝ) :
    Tendsto
      (fun n : ℕ =>
        (((2 * n + 1 : ℕ) : ℝ)⁻¹) *
          ((n : ℝ) * (a + b) + a))
      atTop (𝓝 ((a + b) / 2)) := by
  have hzero :
      Tendsto
        (fun n : ℕ => ((a - b) / 2) *
          (1 / ((2 * n + 1 : ℕ) : ℝ)))
        atTop (𝓝 0) := by
    simpa using
      (tendsto_const_nhds.mul tendsto_inv_odd_nat :
        Tendsto
          (fun n : ℕ => ((a - b) / 2) *
            (1 / ((2 * n + 1 : ℕ) : ℝ)))
          atTop (𝓝 (((a - b) / 2) * 0)))
  have h :=
    tendsto_const_nhds.add hzero
  apply h.congr'
  filter_upwards with n
  exact (odd_average_p0_identity a b n).symm

theorem tendsto_odd_average_p1 (a b : ℝ) :
    Tendsto
      (fun n : ℕ =>
        (((2 * n + 1 : ℕ) : ℝ)⁻¹) *
          ((n : ℝ) * (a + b) + b))
      atTop (𝓝 ((a + b) / 2)) := by
  have hzero :
      Tendsto
        (fun n : ℕ => ((b - a) / 2) *
          (1 / ((2 * n + 1 : ℕ) : ℝ)))
        atTop (𝓝 0) := by
    simpa using
      (tendsto_const_nhds.mul tendsto_inv_odd_nat :
        Tendsto
          (fun n : ℕ => ((b - a) / 2) *
            (1 / ((2 * n + 1 : ℕ) : ℝ)))
          atTop (𝓝 (((b - a) / 2) * 0)))
  have h :=
    tendsto_const_nhds.add hzero
  apply h.congr'
  filter_upwards with n
  exact (odd_average_p1_identity a b n).symm


theorem empiricalIntegral_orbit_p0_tendsto (f : Y → ℝ) :
    Tendsto
      (fun n : ℕ =>
        ∫ y, f y ∂(RegimeSpecification.empiricalOccupation
          spec (orbit p0) (n + 1) (Nat.succ_pos n)))
      atTop
      (𝓝 (∫ y, f y ∂target)) := by
  rw [integral_target_eq_half_sum]
  apply tendsto_of_even_odd
  · have h := tendsto_odd_average_p0 (f p0) (f p1)
    apply h.congr'
    filter_upwards with n
    rw [integral_empiricalOccupation_eq_average]
    rw [Fin.sum_univ_eq_sum_range]
    rw [sum_orbit_p0_odd]
    simp only [Nat.cast_add, Nat.cast_mul, Nat.cast_ofNat]
    rfl
  · apply tendsto_const_nhds.congr'
    filter_upwards with n
    rw [integral_empiricalOccupation_eq_average]
    rw [Fin.sum_univ_eq_sum_range]
    have hhor : 2 * n + 1 + 1 = 2 * (n + 1) := by omega
    rw [hhor, sum_orbit_p0_even]
    simp only [Nat.cast_mul, Nat.cast_add, Nat.cast_one, Nat.cast_ofNat]
    have hn : ((n : ℝ) + 1) ≠ 0 := by positivity
    field_simp [hn]
    ring

theorem empiricalIntegral_orbit_p1_tendsto (f : Y → ℝ) :
    Tendsto
      (fun n : ℕ =>
        ∫ y, f y ∂(RegimeSpecification.empiricalOccupation
          spec (orbit p1) (n + 1) (Nat.succ_pos n)))
      atTop
      (𝓝 (∫ y, f y ∂target)) := by
  rw [integral_target_eq_half_sum]
  apply tendsto_of_even_odd
  · have h := tendsto_odd_average_p1 (f p0) (f p1)
    apply h.congr'
    filter_upwards with n
    rw [integral_empiricalOccupation_eq_average]
    rw [Fin.sum_univ_eq_sum_range]
    rw [sum_orbit_p1_odd]
    simp only [Nat.cast_add, Nat.cast_mul, Nat.cast_ofNat]
    rfl
  · apply tendsto_const_nhds.congr'
    filter_upwards with n
    rw [integral_empiricalOccupation_eq_average]
    rw [Fin.sum_univ_eq_sum_range]
    have hhor : 2 * n + 1 + 1 = 2 * (n + 1) := by omega
    rw [hhor, sum_orbit_p1_even]
    simp only [Nat.cast_mul, Nat.cast_add, Nat.cast_one, Nat.cast_ofNat]
    have hn : ((n : ℝ) + 1) ≠ 0 := by positivity
    field_simp [hn]
    ring

theorem empiricalOccupation_orbit_p0_tendsto :
    Tendsto
      (fun n : ℕ => RegimeSpecification.empiricalOccupation
        spec (orbit p0) (n + 1) (Nat.succ_pos n))
      atTop (𝓝 target) := by
  apply ProbabilityMeasure.tendsto_iff_forall_integral_tendsto.mpr
  intro f
  simpa using empiricalIntegral_orbit_p0_tendsto (fun y => f y)

theorem empiricalOccupation_orbit_p1_tendsto :
    Tendsto
      (fun n : ℕ => RegimeSpecification.empiricalOccupation
        spec (orbit p1) (n + 1) (Nat.succ_pos n))
      atTop (𝓝 target) := by
  apply ProbabilityMeasure.tendsto_iff_forall_integral_tendsto.mpr
  intro f
  simpa using empiricalIntegral_orbit_p1_tendsto (fun y => f y)


theorem stationaryHistoryKernel_orbit (y : Y) (n : ℕ) :
    StrategicWorldModel.stationaryHistoryKernel model.inducedKernel n
        (Preorder.frestrictLe n (orbit y)) =
      Measure.dirac (orbit y (n + 1)) := by
  rw [StrategicWorldModel.stationaryHistoryKernel, Kernel.comap_apply]
  rw [inducedKernel_eq_dirac_step]
  rfl

theorem diracOrbit_hasTransitionPair (y : Y) :
    StrategicWorldModel.HasTransitionPair
      (Measure.dirac (orbit y)) model.inducedKernel := by
  intro n
  ext E hE
  rw [Measure.map_dirac' (by fun_prop)]
  rw [MeasureTheory.dirac_compProd_apply hE]
  rw [stationaryHistoryKernel_orbit]
  rw [Measure.map_dirac' (by fun_prop)]
  rw [Measure.dirac_apply' _ (hE.preimage (by fun_prop))]
  rw [Measure.dirac_apply' _ hE]
  rfl

theorem diracOrbit_pathSpec (y : Y) :
    StrategicWorldModel.MarkovPathLawSpec model (Measure.dirac y)
      (Measure.dirac (orbit y)) := by
  refine ⟨inferInstance, ?_, diracOrbit_hasTransitionPair y⟩
  rw [Measure.map_dirac' (by fun_prop), Measure.map_dirac' (by fun_prop)]
  rfl

theorem pathLaw_dirac_eq_dirac_orbit (y : Y) :
    model.pathLaw (Measure.dirac y) = Measure.dirac (orbit y) := by
  exact (StrategicWorldModel.pathLaw_existsUnique model (Measure.dirac y)).unique
    (Measure.dirac (orbit y)) (diracOrbit_pathSpec y)


theorem measurable_orbit : Measurable orbit :=
  Measurable.of_discrete _

theorem stationaryHistoryKernel_eq_deterministic (n : ℕ) :
    StrategicWorldModel.stationaryHistoryKernel model.inducedKernel n =
      Kernel.deterministic
        (fun h : (i : Finset.Iic n) → Y =>
          step (h ⟨n, Finset.mem_Iic.mpr le_rfl⟩))
        (by fun_prop) := by
  ext h E hE
  rw [StrategicWorldModel.stationaryHistoryKernel, Kernel.comap_apply]
  rw [inducedKernel_eq_dirac_step]
  rw [Kernel.deterministic_apply]
  rfl

/-- For an arbitrary initial probability law, deterministic dynamics push the
initial law forward along the measurable alternating-orbit map. -/
noncomputable def orbitLaw (initLaw : ProbabilityMeasure Y) :
    Measure (ℕ → Y) :=
  initLaw.toMeasure.map orbit

instance orbitLaw_isProbability (initLaw : ProbabilityMeasure Y) :
    IsProbabilityMeasure (orbitLaw initLaw) := by
  unfold orbitLaw
  infer_instance

theorem orbitLaw_initialPrefix (initLaw : ProbabilityMeasure Y) :
    (orbitLaw initLaw).map (Preorder.frestrictLe 0) =
      initLaw.toMeasure.map
        (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => Y)).symm := by
  unfold orbitLaw
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  apply Measure.map_congr
  filter_upwards [] with y
  funext i
  have hi : i.1 = 0 := by
    exact Nat.eq_zero_of_le_zero (Finset.mem_Iic.mp i.2)
  subst i
  rfl

theorem orbitLaw_hasTransitionPair (initLaw : ProbabilityMeasure Y) :
    StrategicWorldModel.HasTransitionPair
      (orbitLaw initLaw) model.inducedKernel := by
  intro n
  rw [stationaryHistoryKernel_eq_deterministic n]
  rw [Measure.compProd_deterministic]
  unfold orbitLaw
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  rw [Measure.map_map (by fun_prop) (by fun_prop)]
  apply Measure.map_congr
  filter_upwards [] with y
  simp only [Function.comp_apply]
  congr
  exact orbit_succ y n

theorem orbitLaw_pathSpec (initLaw : ProbabilityMeasure Y) :
    StrategicWorldModel.MarkovPathLawSpec model initLaw.toMeasure
      (orbitLaw initLaw) := by
  exact ⟨inferInstance, orbitLaw_initialPrefix initLaw,
    orbitLaw_hasTransitionPair initLaw⟩

theorem pathLaw_eq_orbitLaw (initLaw : ProbabilityMeasure Y) :
    model.pathLaw initLaw.toMeasure = orbitLaw initLaw := by
  exact
    (StrategicWorldModel.pathLaw_existsUnique model initLaw.toMeasure).unique
      (orbitLaw initLaw) (orbitLaw_pathSpec initLaw)


def periodicPaths : Set (ℕ → Y) :=
  {orbit p0, orbit p1}

theorem periodicPaths_measurable : MeasurableSet periodicPaths := by
  simp [periodicPaths]

theorem orbit_mem_periodicPaths_of_region
    {y : Y} (hy : y ∈ region) :
    orbit y ∈ periodicPaths := by
  rcases region_cases hy with rfl | rfl <;>
    simp [periodicPaths]

theorem orbitLaw_ae_periodic
    (initLaw : ProbabilityMeasure Y)
    (hinit : IsAdmissibleInitialLaw spec initLaw) :
    ∀ᵐ w ∂orbitLaw initLaw, w ∈ periodicPaths := by
  have hmass : initLaw.toMeasure spec.region = 1 :=
    admissible_mass_region spec initLaw hinit
  have hregion : ∀ᵐ y ∂initLaw.toMeasure, y ∈ region := by
    apply
      (ae_mem_iff_measure_eq
        spec.region_measurable.nullMeasurableSet).2
    simpa [spec] using hmass
  unfold orbitLaw
  rw [ae_map_iff measurable_orbit.aemeasurable periodicPaths_measurable]
  filter_upwards [hregion] with y hy
  exact orbit_mem_periodicPaths_of_region hy

theorem limitingOccupation
    (initLaw : ProbabilityMeasure Y)
    (hinit : IsAdmissibleInitialLaw spec initLaw) :
    IsLimitingOccupationLaw model spec initLaw := by
  unfold IsLimitingOccupationLaw
  change
    ∀ᵐ w ∂model.pathLaw initLaw.toMeasure,
      Tendsto
        (fun n : ℕ => RegimeSpecification.empiricalOccupation
          spec w (n + 1) (Nat.succ_pos n))
        atTop (𝓝 target)
  rw [pathLaw_eq_orbitLaw]
  filter_upwards [orbitLaw_ae_periodic initLaw hinit] with w hw
  rcases hw with hw | hw
  · rw [hw]
    exact empiricalOccupation_orbit_p0_tendsto
  · rw [hw]
    exact empiricalOccupation_orbit_p1_tendsto

/-- Proposition 8.1 core certificate: the literal two-cycle is an Exact
Generated Regime under almost-sure weak occupation convergence. -/
theorem periodic_isExactGeneratedRegime :
    IsExactGeneratedRegime model spec referenceMeasure := by
  refine ⟨canonicalProcessWellPosed model, assumption41, exactlyInvariant, ?_⟩
  intro initLaw hinit
  exact limitingOccupation initLaw hinit

/-- Proposition 8.1 in the paper-level ambient wrapper. -/
theorem proposition_8_1 :
    IsPaperExactGeneratedRegime model spec referenceMeasure :=
  periodic_isExactGeneratedRegime

end

end PeriodicExactGR

end PermanssonLean
