import PermanssonLean.Regime.PolishDescriptor
import Mathlib.Probability.Kernel.Deterministic
import Mathlib.MeasureTheory.Measure.Count

open Filter MeasureTheory ProbabilityTheory Set
open scoped ENNReal ProbabilityTheory Topology

namespace PermanssonLean

open RegimeSpecification

/-!
# Proposition 8.1: periodic Exact Generated Regime

This module formalizes the literal two-state example from Section 8.1 of
Permansson v0.1.7.  We encode 0/1 by Bool false/true.
-/

namespace PeriodicExactGR

noncomputable section

abbrev Bit := Bool
abbrev Y := JointState Bit Bit

def p0 : Y := (false, false)
def p1 : Y := (true, true)

def flipBit (b : Bit) : Bit := !b

def step (y : Y) : Y := (flipBit y.1, flipBit y.1)

@[simp] theorem step_p0 : step p0 = p1 := by
  rfl

@[simp] theorem step_p1 : step p1 = p0 := by
  rfl

def actionKernel : Kernel Y Bit :=
  Kernel.deterministic (fun y => y.1) (by fun_prop)

def worldKernel : Kernel (WorldInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.2) (by fun_prop)

def updateKernel : Kernel (UpdateInput Bit Bit Bit) Bit :=
  Kernel.deterministic (fun z => !z.1.1.1) (by fun_prop)

def generator : StrategicGenerator Bit Bit Bit where
  action := actionKernel
  update := updateKernel
  action_isMarkov := by
    unfold actionKernel
    infer_instance
  update_isMarkov := by
    unfold updateKernel
    infer_instance

def model : StrategicWorldModel Bit Bit Bit where
  generator := generator
  world := worldKernel
  world_isMarkov := by
    unfold worldKernel
    infer_instance

theorem inducedKernel_eq_dirac_step (y : Y) :
    model.inducedKernel y = Measure.dirac (step y) := by
  ext E hE
  rw [StrategicWorldModel.inducedKernel_apply model y hE]
  simp [model, generator, actionKernel, worldKernel, updateKernel, step,
    flipBit, Kernel.deterministic_apply]
  by_cases hmem : step y ∈ E <;> simp [hmem, step, flipBit]

def region : Set Y := {p0, p1}

def basin : Set Y := region

def phase : Fin 2 → Y
  | ⟨0, _⟩ => p0
  | ⟨1, _⟩ => p1

/-- Equation (20): the equally weighted occupation law on the two-cycle. -/
noncomputable def targetMeasure : Measure Y :=
  (1 / 2 : ℝ≥0∞) • Measure.dirac p0 +
    (1 / 2 : ℝ≥0∞) • Measure.dirac p1

instance targetMeasure_isProbability :
    IsProbabilityMeasure targetMeasure := by
  refine ⟨?_⟩
  simp [targetMeasure]
  norm_num

noncomputable def target : ProbabilityMeasure Y :=
  targetMeasure.toProbabilityMeasure

@[simp] theorem target_toMeasure :
    target.toMeasure = targetMeasure := by
  rfl

noncomputable def spec : RegimeSpecification Y Y where
  region := region
  region_measurable := MeasurableSet.of_discrete
  basin := basin
  basin_measurable := MeasurableSet.of_discrete
  basin_subset_region := by
    intro y hy
    exact hy
  descriptor := id
  descriptor_measurable := measurable_id
  target := target
  convergenceMode := ConvergenceMode.almostSureWeak Y Y

noncomputable def referenceMeasure : Measure Y :=
  Measure.count

@[simp] theorem p0_mem_region : p0 ∈ region := by
  simp [region]

@[simp] theorem p1_mem_region : p1 ∈ region := by
  simp [region]

theorem region_cases {y : Y} (hy : y ∈ region) :
    y = p0 ∨ y = p1 := by
  simpa [region] using hy

theorem step_mem_region {y : Y} (hy : y ∈ region) :
    step y ∈ region := by
  rcases region_cases hy with rfl | rfl <;> simp

theorem exactlyInvariant :
    IsExactlyInvariant model spec := by
  intro y hy
  rw [inducedKernel_eq_dirac_step]
  rw [Measure.dirac_apply_of_mem]
  exact step_mem_region hy

theorem basinHasTwoStates :
    BasinHasTwoStates spec := by
  refine ⟨p0, ?_, p1, ?_, ?_⟩
  · simp [spec, basin, region]
  · simp [spec, basin, region]
  · decide

theorem assumption41 :
    Assumption41 model spec referenceMeasure := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact ⟨p0, by simp [spec, basin, region]⟩
  · left
    refine ⟨p0, ?_⟩
    simp [spec, region]
  · refine ⟨p0, by simp [spec, region], p1, by simp [spec, region], ?_⟩
    decide
  · exact two_states_implies_basinPathLawNontrivial model spec basinHasTwoStates

/-- Deterministic alternating orbit generated by the Section 8.1 transition. -/
def orbit (y : Y) : ℕ → Y
  | 0 => y
  | n + 1 => step (orbit y n)

@[simp] theorem orbit_zero (y : Y) : orbit y 0 = y := rfl

@[simp] theorem orbit_succ (y : Y) (n : ℕ) :
    orbit y (n + 1) = step (orbit y n) := rfl

@[simp] theorem orbit_p0_even (n : ℕ) :
    orbit p0 (2 * n) = p0 := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [Nat.mul_succ, Nat.mul_one, Nat.add_assoc]
      simp only [Nat.add_comm 2 (2 * n)]
      rw [show 2 * n + 2 = (2 * n + 1) + 1 by omega]
      simp [orbit_succ, ih]


theorem stationaryHistoryKernel_orbit (y : Y) (n : ℕ) :
    StrategicWorldModel.stationaryHistoryKernel model.inducedKernel n
        (Preorder.frestrictLe n (orbit y)) =
      Measure.dirac (orbit y (n + 1)) := by
  rw [StrategicWorldModel.stationaryHistoryKernel, Kernel.comap_apply]
  rw [inducedKernel_eq_dirac_step]
  rfl

theorem diracOrbit_hasTransitionPair (y : Y) :
    StrategicWorldModel.HasTransitionPair
      (Measure.dirac (orbit y)) model.inducedKernel := by
  intro n
  ext E hE
  rw [Measure.map_dirac' (by fun_prop)]
  rw [MeasureTheory.dirac_compProd_apply hE]
  rw [stationaryHistoryKernel_orbit]
  rw [Measure.map_dirac' (by fun_prop)]
  rw [Measure.dirac_apply' _ (hE.preimage (by fun_prop))]
  rw [Measure.dirac_apply' _ hE]
  rfl

theorem diracOrbit_pathSpec (y : Y) :
    StrategicWorldModel.MarkovPathLawSpec model (Measure.dirac y)
      (Measure.dirac (orbit y)) := by
  refine ⟨inferInstance, ?_, diracOrbit_hasTransitionPair y⟩
  rw [Measure.map_dirac' (by fun_prop), Measure.map_dirac' (by fun_prop)]
  rfl

theorem pathLaw_dirac_eq_dirac_orbit (y : Y) :
    model.pathLaw (Measure.dirac y) = Measure.dirac (orbit y) := by
  exact (StrategicWorldModel.pathLaw_existsUnique model (Measure.dirac y)).unique
    (Measure.dirac (orbit y)) (diracOrbit_pathSpec y)


theorem measurable_orbit : Measurable orbit :=
  Measurable.of_discrete _

theorem stationaryHistoryKernel_eq_deterministic (n : ℕ) :
    StrategicWorldModel.stationaryHistoryKernel model.inducedKernel n =
      Kernel.deterministic
        (fun h : (i : Finset.Iic n) → Y =>
          step (h ⟨n, Finset.mem_Iic.mpr le_rfl⟩))
        (by fun_prop) := by
  ext h E hE
  rw [StrategicWorldModel.stationaryHistoryKernel, Kernel.comap_apply]
  rw [inducedKernel_eq_dirac_step]
  rw [Kernel.deterministic_apply]
  rfl

/-- For an arbitrary initial probability law, deterministic dynamics push the
initial law forward along the measurable alternating-orbit map. -/
noncomputable def orbitLaw (initLaw : ProbabilityMeasure Y) :
    Measure (ℕ → Y) :=
  initLaw.toMeasure.map orbit

instance orbitLaw_isProbability (initLaw : ProbabilityMeasure Y) :
    IsProbabilityMeasure (orbitLaw initLaw) := by
  unfold orbitLaw
  infer_instance

theorem orbitLaw_initialPrefix (initLaw : ProbabilityMeasure Y) :
    (orbitLaw initLaw).map (Preorder.frestrictLe 0) =
      initLaw.toMeasure.map
        (MeasurableEquiv.piUnique (fun _ : Finset.Iic 0 => Y)).symm := by
  unfold orbitLaw
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  apply Measure.map_congr
  filter_upwards [] with y
  funext i
  have hi : i.1 = 0 := by
    exact Nat.eq_zero_of_le_zero (Finset.mem_Iic.mp i.2)
  subst i
  rfl

theorem orbitLaw_hasTransitionPair (initLaw : ProbabilityMeasure Y) :
    StrategicWorldModel.HasTransitionPair
      (orbitLaw initLaw) model.inducedKernel := by
  intro n
  rw [stationaryHistoryKernel_eq_deterministic n]
  rw [Measure.compProd_deterministic]
  unfold orbitLaw
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  rw [Measure.map_map (by fun_prop) measurable_orbit]
  rw [Measure.map_map (by fun_prop) (by fun_prop)]
  apply Measure.map_congr
  filter_upwards [] with y
  simp only [Function.comp_apply]
  congr
  exact orbit_succ y n

theorem orbitLaw_pathSpec (initLaw : ProbabilityMeasure Y) :
    StrategicWorldModel.MarkovPathLawSpec model initLaw.toMeasure
      (orbitLaw initLaw) := by
  exact ⟨inferInstance, orbitLaw_initialPrefix initLaw,
    orbitLaw_hasTransitionPair initLaw⟩

theorem pathLaw_eq_orbitLaw (initLaw : ProbabilityMeasure Y) :
    model.pathLaw initLaw.toMeasure = orbitLaw initLaw := by
  exact
    (StrategicWorldModel.pathLaw_existsUnique model initLaw.toMeasure).unique
      (orbitLaw initLaw) (orbitLaw_pathSpec initLaw)

end

end PeriodicExactGR

end PermanssonLean
