import PermanssonLean.Probability.CommonPartKernel
import Mathlib.Probability.Kernel.IonescuTulcea.PartialTraj
import Mathlib.MeasureTheory.Measure.AEMeasurable

open Finset MeasureTheory ProbabilityTheory Set
open scoped ENNReal ProbabilityTheory

namespace PermanssonLean
namespace ProbabilitySupport

universe uY uZ

variable {Y : Type uY} {Z : Type uZ}
variable [MeasurableSpace Y] [MeasurableSpace Z]

/-!
# Finite-prefix total-variation propagation

This file develops the pathwise half of Proposition 5.4.  The merged support
layers already provide the source-faithful event-TV convention, the geometric
envelope, and a measurable common-part kernel whose one-step retained mass is
at least `1 - ε` under a uniform TV hypothesis.

The current layer adds the generic common-submeasure TV estimate and freezes a
finite-prefix representation through mathlib's `partialTraj` API.  The
remaining induction propagates the common-part subkernel through those finite
prefixes.
-/

/-- If a finite measure `ξ` is dominated by probability measures `μ` and
`ν`, then their event total variation is bounded by the mass missing from
`ξ`.  This is the measure-theoretic endpoint used after constructing a common
finite-prefix submeasure. -/
theorem eventTotalVariation_le_one_sub_commonMass
    {μ ν ξ : Measure Y}
    [IsProbabilityMeasure μ] [IsProbabilityMeasure ν] [IsFiniteMeasure ξ]
    (hξμ : ξ ≤ μ) (hξν : ξ ≤ ν) :
    eventTotalVariation μ ν ≤ 1 - ξ.real Set.univ := by
  unfold eventTotalVariation
  apply csSup_le (eventTVCandidates_nonempty μ ν)
  intro r hr
  rcases hr with ⟨s, hs, rfl⟩
  have hμcomp : μ.real s + μ.real sᶜ = 1 :=
    probReal_add_probReal_compl hs
  have hνcomp : ν.real s + ν.real sᶜ = 1 :=
    probReal_add_probReal_compl hs
  have hξcomp : ξ.real s + ξ.real sᶜ = ξ.real Set.univ := by
    have h := congrArg ENNReal.toReal (measure_add_measure_compl hs (μ := ξ))
    simpa [Measure.real, ENNReal.toReal_add] using h
  have hξμs : ξ.real s ≤ μ.real s :=
    ENNReal.toReal_mono (by finiteness) (hξμ s)
  have hξνs : ξ.real s ≤ ν.real s :=
    ENNReal.toReal_mono (by finiteness) (hξν s)
  have hξμc : ξ.real sᶜ ≤ μ.real sᶜ :=
    ENNReal.toReal_mono (by finiteness) (hξμ sᶜ)
  have hξνc : ξ.real sᶜ ≤ ν.real sᶜ :=
    ENNReal.toReal_mono (by finiteness) (hξν sᶜ)
  rw [abs_le]
  constructor <;> linarith

/-- Stationary one-step kernel lifted to a finite history by reading only the
latest coordinate.  This is the generic version of the construction used by
`StrategicWorldModel.pathLaw`. -/
noncomputable def stationaryPrefixKernel
    (K : Kernel Y Y) (n : ℕ) :
    Kernel ((i : Finset.Iic n) → Y) Y :=
  K.comap (fun h => h ⟨n, Finset.mem_Iic.mpr le_rfl⟩) (by fun_prop)

instance stationaryPrefixKernel_isMarkov
    (K : Kernel Y Y) [IsMarkovKernel K] (n : ℕ) :
    IsMarkovKernel (stationaryPrefixKernel K n) := by
  unfold stationaryPrefixKernel
  infer_instance

instance stationaryPrefixKernel_isFinite
    (K : Kernel Y Y) [IsFiniteKernel K] (n : ℕ) :
    IsFiniteKernel (stationaryPrefixKernel K n) := by
  unfold stationaryPrefixKernel
  infer_instance

/-- The unique length-zero history concentrated at `y`. -/
def singletonPrefix (y : Y) : (i : Finset.Iic 0) → Y :=
  fun _ => y

/-- Finite prefix law through `T` transitions for a stationary kernel,
started from the point state `y`.  The codomain records times `0,...,T`. -/
noncomputable def finitePrefixLaw
    (K : Kernel Y Y) (y : Y) (T : ℕ) :
    Measure ((i : Finset.Iic T) → Y) :=
  Kernel.partialTraj (fun n => stationaryPrefixKernel K n) 0 T (singletonPrefix y)

instance finitePrefixLaw_isProbability
    (K : Kernel Y Y) [IsMarkovKernel K] (y : Y) (T : ℕ) :
    IsProbabilityMeasure (finitePrefixLaw K y T) := by
  unfold finitePrefixLaw
  infer_instance

/-- Finite prefix submeasure generated by the measurable common-part kernel. -/
noncomputable def commonFinitePrefixLaw
    [MeasurableSpace.CountableOrCountablyGenerated Y Y]
    (K Ktilde : Kernel Y Y) [IsMarkovKernel K] [IsMarkovKernel Ktilde]
    (y : Y) (T : ℕ) :
    Measure ((i : Finset.Iic T) → Y) :=
  finitePrefixLaw (commonPartKernel K Ktilde) y T

instance commonFinitePrefixLaw_isFinite
    [MeasurableSpace.CountableOrCountablyGenerated Y Y]
    (K Ktilde : Kernel Y Y) [IsMarkovKernel K] [IsMarkovKernel Ktilde]
    (y : Y) (T : ℕ) :
    IsFiniteMeasure (commonFinitePrefixLaw K Ktilde y T) := by
  unfold commonFinitePrefixLaw finitePrefixLaw
  infer_instance

/-- Kernel composition is monotone simultaneously in both arguments. -/
theorem kernelComp_mono
    {κ κ' : Kernel Y Z} {η η' : Kernel Z Y}
    [IsSFiniteKernel κ] [IsSFiniteKernel κ']
    [IsSFiniteKernel η] [IsSFiniteKernel η']
    (hκ : κ ≤ κ') (hη : η ≤ η') :
    η ∘ₖ κ ≤ η' ∘ₖ κ' := by
  intro y
  rw [Kernel.comp_apply, Kernel.comp_apply]
  apply Measure.le_iff.2
  intro s hs
  rw [Measure.bind_apply hs (Kernel.aemeasurable η),
      Measure.bind_apply hs (Kernel.aemeasurable η')]
  exact lintegral_mono' (hκ y) (fun z => hη z s)

/-- Measurable maps preserve measure domination. -/
theorem measureMap_mono
    {μ ν : Measure Y} (hμν : μ ≤ ν)
    {f : Y → Z} (hf : Measurable f) :
    μ.map f ≤ ν.map f :=
  Measure.map_mono_of_aemeasurable hμν hf.aemeasurable

end ProbabilitySupport
end PermanssonLean
